import { ApiProperty } from '@nestjs/swagger'
import { Project as ProjectType } from '@prisma/client'
import { IsOptional, IsString, IsUrl, IsUUID } from 'class-validator'

export class Project implements ProjectType {
  @ApiProperty({
    example: '4e8b9963-f72d-4887-9678-48c3ff26d60e',
  })
  @IsUUID()
  uid: string

  @ApiProperty({
    example: 'Perfumest',
  })
  @IsString()
  name: string

  @ApiProperty({
    example: 'https://i.imgur.com/djaSRcV.png',
    description: 'Mobile Preview Image(optional)',
    format: 'link',
    required: false,
    nullable: true,
  })
  @IsOptional()
  preview_mobile: string

  @ApiProperty({
    example: 'https://i.imgur.com/PdNzBow_d.webp?maxwidth=760&fidelity=grand',
    description: 'Desktop Preview Image',
    format: 'link',
  })
  @IsUrl()
  preview: string

  @ApiProperty({
    example: 'https://www.perfumest.one/',
    description: 'Website link',
  })
  @IsUrl()
  link: string

  @ApiProperty({
    example: '2024-12-16T19:13:25.284Z',
    description: 'Creation Date(autogenerated)',
    format: 'ISODate',
  })
  createdAt: Date

  @ApiProperty({
    example: '2024-12-16T19:12:51.551Z',
    description: 'Update Date(autogenerated)',
    format: 'ISODate',
  })
  updatedAt: Date
}
